name: RFC XML Check

on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt-get install -y aspell cmake python3 python3-pip python3-setuptools python3-wheel ruby xmlstarlet yajl-tools xml2rfc
        sudo pip3 install xml2rfc
        sudo gem install cddl
    - name: xml2rfc
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_DOCDIR=$PWD/build/install
        cmake --build build -v
        cmake --install build
    - uses: actions/upload-artifact@v3
      with:
        name: spec
        path: build/install

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: spec
        path: build/install
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build/install # The folder the action should deploy.
